### ISSUE TITLE
ndarray -> opencv conversion

### ISSUE THREAD

**Issue by mdrokz** [jerry73204/rust-cv-convert#12]
Hi im working on converting an ML model and i want to convert an `ArrayBase<OwnedRepr<f32>, Dim<[usize; 2]>>`  to `opencv::core::Mat` so i can use it in `fill_poly` method of opencv, is there any way to do this ?

**Comment by jerry73204** [comment]
Now it's implemented in 0.24.1. Please enjoy it.

**Comment by mdrokz** [comment]
> Now it's implemented in 0.24.1. Please enjoy it.

Thanks :) i will try it when i get some time if i encounter any issues i will inform here.
