### ISSUE TITLE
Some documentation needed. 

### ISSUE THREAD

**Issue by Barafu** [jerry73204/rust-cv-convert#4]
At least some examples are needed. I can not understand how to use this crate convert Rust image into opencv, for example.

**Comment by YuanYuYuan** [comment]
I just made a PR #5, hope this would help you.

You can convert the Rust image to opencv Mat by, for example,

```rust
use anyhow::Result;
use cv_convert::{TryFromCv, TryIntoCv};
use opencv::{self as cv, highgui, imgcodecs};

fn main() -> Result<()> {
    let path = "YOUR_IMAGE_PATH";
    let img = image::io::Reader::open(&path)?.decode()?;
    let mat: cv::core::Mat = img.try_into_cv()?;
    highgui::imshow("Image-to-OpenCV", &mat)?;
    highgui::wait_key(0)?;
    Ok(())
}
```

**Comment by jerry73204** [comment]
Now the API doc ([link](https://docs.rs/cv-convert/latest/cv_convert/)) includes a working example.
