### ISSUE TITLE
Help: Convert opencv image to ndarray

### ISSUE THREAD

**Issue by Machine-Jonte** [jerry73204/rust-cv-convert#6]
Hello!
This is a very promising package (thanks for putting in the effort of making it). 

I've been struggling to figure out how to convert opencv::core::Mat -> Array3<u8>.
Is this possible? Seems from the README the answer should be yes!

Following the README I expect to do something like:
```rust
    let img = opencv::imgcodecs::imread("./assets/demo_img.jpg", cv::imgcodecs::IMREAD_COLOR)?;
    let img: Array3<u8> = img.try_into_cv()?;
    // or
    let img: ArrayView3<u8> = img.try_into_cv()?;
```

This is my cargo.toml
```
...
[dependencies]
ndarray = "0.15.4"
opencv = {version = "0.63.0", features = ["clang-runtime"]}
cv-convert = {version = "0.17.2", features = ["ndarray_0-15", "opencv_0-63"]}
```

**Comment by jerry73204** [comment]
According to the crate level doc ([link](https://docs.rs/cv-convert/0.16.1/cv_convert/index.html)), the direction opencv -> ndarray is not implemented yet. Perhaps you can open a feature request and let me find some time to work it out

**Comment by Machine-Jonte** [comment]
Yes, my mistake, I missed that in the docs. Thanks for the clarification.
